version: '2.2'
services:
  web:
    image: hojindev/codeigniter_hmvc:latest
    ports:
      - "80:80"
    volumes:
      - $PWD:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT="/var/www/html/m"
